version: '3.8'
services:
  mongo:
    image: mongo
    restart: always
    container_name: genesis
    hostname: local-host-users
    environment:
      MONGO_INITDB_ROOT_USERNAME: less
      MONGO_INITDB_ROOT_PASSWORD: chocorrococo
    volumes:
      - ./data:/data/db
      - ./data/log:/var/log/mongodb/
    ports:
      - "27020:27017"
    expose:
      - 27020